- hosts: localhost
  connection: local
  sudo: yes
  vars:
    db_name: django_app
    db_user: django
    db_password: sdjgh34iutwefhfgbqkj3
    virtualenv_path: /home/travis/build/Cadasta/cadasta-platform/env/
    application_path: /home/travis/build/Cadasta/cadasta-platform/
  roles:
      - common
      - db
      - cadasta_app
      - cadasta_dev
