- name: Manually create the initial virtualenv
  command: virtualenv {{ virtualenv_path }} -p python3 creates="{{ virtualenv_path }}"

- name: Install requirements
  pip: virtualenv={{ virtualenv_path }} requirements={{ application_path }}requirements/common.txt

- name: Django migrate
  django_manage: command=migrate app_path={{ application_path }}cadasta virtualenv={{ virtualenv_path }}
