- name: Install requirements
  pip: virtualenv={{ virtualenv_path }} requirements={{ application_path }}/requirements/common.txt

- name: Django migrate
  django_manage: command=migrate app_path={{ application_path }}/cadasta virtualenv={{ virtualenv_path }}
