---
sudo: required
dist: trusty
language: python
python:
  - "3.5"
addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.1 # Workaround https://github.com/travis-ci/travis-ci/issues/5178
before_install:
  - export DEBIAN_FRONTEND=noninteractive;
    sudo -E apt-get -yq update &>> ~/apt-get-update.log;
    sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.2
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
  - pip install -r requirements/common.txt
  - pip install -r requirements/dev.txt
  - nvm install 4.0.0
  - nvm alias default 4.0.0
before_script:
  - psql template1 postgres -c 'create extension hstore;'
  - psql -c 'create database cadasta;' -U postgres
  - psql -U postgres -d cadasta -c "create extension postgis;"
  - python cadasta/manage.py migrate --settings=config.settings.travis
script:
  - py.test cadasta --cov=cadasta --ds=config.settings.travis
  - cd functional_tests
  - ./run.py --ds=config.settings.travis
