---
language: python
python:
  - "3.4"
services:
  - postgresql
addons:
  postgresql: "9.4"
install:
  - pip install -r requirements/common.txt
  - pip install -r requirements/dev.txt
before_script:
  - psql template1 postgres -c 'create extension hstore;'
  - psql -c 'create database cadasta;' -U postgres
  - psql -U postgres -d cadasta -c "create extension postgis;"
  - python cadasta/manage.py migrate
script:
  - py.test cadasta --cov=cadasta --ds=config.settings.travis
