- name: Add nginx/stable repository
  sudo: yes
  apt_repository: repo='ppa:nginx/stable'

- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - nginx

- name: write precise64 to sites-available
  action: template src=precise64.j2 dest=/etc/nginx/sites-available/{{ server_name }}
  sudo: True

- name: enable site precise64
  action: file src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link
  sudo: True
  notify:
    - restart nginx
