- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:

      # Python Dev
      - python3
      - python3-dev
      - python-setuptools
      - python-virtualenv
      - nginx

- name: write precise64 to sites-available
  action: template src=precise64.j2 dest=/etc/nginx/sites-available/{{ server_name }}
  sudo: True

- name: enable site precise64
  action: file src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link
  sudo: True
  notify:
    - restart nginx

- name: Manually create the initial virtualenv
  command: virtualenv {{ virtualenv_path }} -p python3 creates="{{ virtualenv_path }}"

- name: Install requirements
  pip: virtualenv={{ virtualenv_path }} requirements={{ application_path }}/requirements/common.txt

- name: Django migrate
  django_manage: command=migrate app_path={{ application_path }}/app virtualenv={{ virtualenv_path }}
