- name: Install Firefox and Xvfb
  become: yes
  become_user: root
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - firefox
      - xvfb

- name: Install Python Selenium driver
  become: yes
  become_user: "{{ app_user }}"
  pip: virtualenv="{{ virtualenv_path }}"
       name=selenium
