- name: Install requirements
  pip: virtualenv={{ virtualenv_path }} requirements={{ application_path }}requirements/dev.txt

- name: Activate virtual environment on VM login
  become: yes
  become_user: "{{ app_user }}"
  lineinfile: dest=/home/vagrant/.bashrc
              line=". /opt/cadasta/env/bin/activate"

- name: Go to cadasta-platform root on VM login
  become: yes
  become_user: "{{ app_user }}"
  lineinfile: dest=/home/vagrant/.bashrc
              line="cd /vagrant"

- name: Install gettext translation utilities
  become: yes
  become_user: root
  apt: pkg=gettext state=installed update_cache=yes

- name: Make Transifex credentials file link
  file: state=link force=yes
        path=/home/vagrant/.transifexrc src=/vagrant/.transifexrc
