- name: Add deadsnakes Python repository
  become: yes
  become_user: root
  apt_repository: repo='ppa:fkrull/deadsnakes'

- name: Install packages
  become: yes
  become_user: root
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - python3.5
      - python3.5-dev
      - python-virtualenv
      - git

- name: Install SASS
  become: yes
  become_user: root
  command: gem install sass

- name: Create base directory for virtual environment
  become: yes
  become_user: root
  file: path="{{ virtualenv_path | dirname }}" state=directory
        owner="{{ app_user }}" mode=0755

- name: Manually create the initial virtualenv
  become: yes
  become_user: "{{ app_user }}"
  command: virtualenv {{ virtualenv_path }} --python=python3.5
           creates="{{ virtualenv_path }}bin"

- name: Install requirements
  become: yes
  become_user: "{{ app_user }}"
  pip: virtualenv="{{ virtualenv_path }}"
       requirements="{{ application_path }}requirements/common.txt"

- name: Set up logging directory
  become: yes
  become_user: root
  file: path=/var/log/django state=directory owner="{{ app_user }}"

- name: Django migrate
  become: yes
  become_user: "{{ app_user }}"
  django_manage: command=migrate
                 app_path="{{ application_path }}cadasta"
                 virtualenv="{{ virtualenv_path }}"
                 settings="{{ django_settings }}"

- name: Install Bootstrap for SASS processing
  become: yes
  become_user: "{{ app_user }}"
  command: chdir="{{ application_path }}cadasta/core/sass"
           npm install bootstrap-sass

- name: Convert SASS to CSS
  become: yes
  become_user: "{{ app_user }}"
  command: chdir="{{ application_path }}cadasta/core/sass"
           sass -I ./node_modules main.scss ../static/css/main.css
